// lib/domain/entities/scenario.dart

/// The type of a scenario generated by the AI.
enum ScenarioType {
  good,
  neutral,
  bad;

  String get value => name;

  static ScenarioType fromValue(String value) {
    return ScenarioType.values.firstWhere(
      (e) => e.name == value,
      orElse: () => ScenarioType.neutral,
    );
  }
}

/// Immutable domain entity representing a single scenario
/// generated by the AI for a decision.
class Scenario {
  final String id; // UUID v4
  final String decisionId; // FK -> Decision.id
  final ScenarioType type;
  final String description;
  final double probability; // 0.0 to 1.0, all 3 must sum to 1.0
  final List<String> positiveEffects;
  final List<String> negativeEffects;
  final String recommendation;

  const Scenario({
    required this.id,
    required this.decisionId,
    required this.type,
    required this.description,
    required this.probability,
    this.positiveEffects = const [],
    this.negativeEffects = const [],
    this.recommendation = '',
  });

  Scenario copyWith({
    String? id,
    String? decisionId,
    ScenarioType? type,
    String? description,
    double? probability,
    List<String>? positiveEffects,
    List<String>? negativeEffects,
    String? recommendation,
  }) {
    return Scenario(
      id: id ?? this.id,
      decisionId: decisionId ?? this.decisionId,
      type: type ?? this.type,
      description: description ?? this.description,
      probability: probability ?? this.probability,
      positiveEffects: positiveEffects ?? this.positiveEffects,
      negativeEffects: negativeEffects ?? this.negativeEffects,
      recommendation: recommendation ?? this.recommendation,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'decision_id': decisionId,
      'type': type.value,
      'description': description,
      'probability': probability,
      'positive_effects': positiveEffects,
      'negative_effects': negativeEffects,
      'recommendation': recommendation,
    };
  }

  factory Scenario.fromMap(Map<String, dynamic> map) {
    return Scenario(
      id: map['id'] as String,
      decisionId: map['decision_id'] as String,
      type: ScenarioType.fromValue(map['type'] as String),
      description: map['description'] as String,
      probability: (map['probability'] as num).toDouble(),
      positiveEffects: (map['positive_effects'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      negativeEffects: (map['negative_effects'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      recommendation: map['recommendation'] as String? ?? '',
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Scenario &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          decisionId == other.decisionId &&
          type == other.type &&
          description == other.description &&
          probability == other.probability;

  @override
  int get hashCode =>
      Object.hash(id, decisionId, type, description, probability);

  @override
  String toString() {
    return 'Scenario(id: $id, type: $type, probability: $probability, '
        'description: $description)';
  }
}
